source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'metadata-json-lint'
gem 'puppet', '3.8.7'
gem 'puppetlabs_spec_helper', '>= 1.0.0'
gem 'puppet-lint', '>= 2.0.0'
gem 'facter'
gem 'rspec-puppet'
gem 'apipie-bindings'
gem 'pry_debug'
gem 'pry-nav'
gem 'pry-stack_explorer'
gem 'json'

gem 'rake'
gem 'rubocop'
